<p class="path"><a href="../pkb.html">pkb contents</a> \> machine learning | nearly 241 words | updated 05/18/2017</p><div class="TOC">- 1. [Sources](#sources)
	- 1.1. [Unread](#unread)
</div>

# 1. Sources

## 1.1. Unread

- [Coursera - Machine Learning Specialization](https://www.coursera.org/specializations/machine-learning)
- [Top 10 Data Mining Algorithms in Plain English](http://rayli.net/blog/data/top-10-data-mining-algorithms-in-plain-english/)
- [Has deep learning made traditional ML irrelevant?](http://www.datasciencecentral.com/profiles/blogs/has-deep-learning-made-traditional-machine-learning-irrelevant)
- [How Google used artificial intelligence to transform Google Translate—and how machine learning is poised to reinvent computing itself](http://www.nytimes.com/2016/12/14/magazine/the-great-ai-awakening.html)
- [https://en.wikipedia.org/wiki/Data_mining](https://en.wikipedia.org/wiki/Data_mining)
- [Essentials of machine learning algorithms](https://www.analyticsvidhya.com/blog/2015/08/common-machine-learning-algorithms/)
- [A tour of ML algorithms](http://www.datasciencecentral.com/profiles/blogs/a-tour-of-machine-learning-algorithms-1)
- [Implementation of 17 classification algorithms in R](http://www.datascience-zing.com/blog/implemetation-of-17-classification-algorithms-in-r-using-car-evaluation-data)
- [Map of Data Mining Techniques](http://saedsayad.com/data_mining_map.htm)
- [R2D3: Visual Intro to Machine Learning](http://www.r2d3.us/visual-intro-to-machine-learning-part-1/)
- [Undergrad ML syllabus](https://piazza.com/umd/fall2015/cmsc422/home)
- [Complete tutorial on tree based modeling](https://www.analyticsvidhya.com/blog/2016/04/complete-tutorial-tree-based-modeling-scratch-in-python/)
- [Machine learning in a week](https://medium.com/learning-new-stuff/machine-learning-in-a-week-a0da25d59850#.r517qamav)
- [Machine learning in a year](https://medium.com/learning-new-stuff/machine-learning-in-a-year-cdb0b0ebd29c#.zg6ty8x8x)
- [In-depth introduction to machine learning (15 hours)](https://www.r-bloggers.com/in-depth-introduction-to-machine-learning-in-15-hours-of-expert-videos/)
- [Power to the People: How One Unknown Group of Researchers Holds the Key to Using AI to Solve Real Human Problems](https://medium.com/@atduskgreg/power-to-the-people-how-one-unknown-group-of-researchers-holds-the-key-to-using-ai-to-solve-real-cc9e75b1f334#.2k74ego8p)
- [DataCamp - Kaggle Python tutorial on Machine Learning](https://www.datacamp.com/courses/kaggle-python-tutorial-on-machine-learning)
- [How to use data analysis for machine learning](http://www.r-bloggers.stfi.re/how-to-use-data-analysis-for-machine-learning-example-part-1/?sf=roexglx#aa)
- [GitHub - Dive into Machine Learning](https://github.com/hangtwenty/dive-into-machine-learning)
- [Udacity - Intro. Machine Learning](https://www.udacity.com/course/intro-to-machine-learning--ud120)
- [Big Data U - Machine Learning with Python](https://bigdatauniversity.com/courses/introduction-to-machine-learning-with-python/)
- [DataCamp - Machine Learning with R](https://www.datacamp.com/courses/introduction-to-machine-learning-with-r)
- [Big Data U - Machine Learning: Cluster Analysis](http://bigdatauniversity.com/courses/machine-learning-cluster-analysis/)
- [A concise history of neural networks](https://medium.com/@Jaconda/a-concise-history-of-neural-networks-2070655d3fec#.b0ip33aeq)
- [A mostly complete chart of neural networks](http://www.asimovinstitute.org/neural-network-zoo/)
- [Understanding neural networks with TensorFlow Playground](https://cloud.google.com/blog/big-data/2016/07/understanding-neural-networks-with-tensorflow-playground)
- [10 deep learning terms explained in simple English](http://www.datasciencecentral.com/profiles/blogs/10-deep-learning-terms-explained-in-simple-english)
- [Deep learning demystified](http://www.datasciencecentral.com/profiles/blogs/deep-learning-demystified)
- [Deep learning simplified (video series)](https://www.youtube.com/channel/UC9OeZkIwhzfv-_Cb7fCikLQ)
- [Deep learning textbook](https://www.youtube.com/channel/UC9OeZkIwhzfv-_Cb7fCikLQ)
- [16 free machine learning books](https://hackerlists.com/free-machine-learning-books/)